name: Run iOS Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-15
    timeout-minutes: 20
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Show Xcode version
      run: xcodebuild -version
    
    - name: Show available simulators
      run: xcrun simctl list devices available | head -20
    
    - name: Resolve Swift Package dependencies
      run: xcodebuild -project Sudoku.xcodeproj -resolvePackageDependencies
    
    - name: Build project for testing
      run: |
        xcodebuild build-for-testing \
          -project Sudoku.xcodeproj \
          -scheme SudokuTests \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          -configuration Debug \
          CODE_SIGNING_ALLOWED=NO
      
    - name: Run tests
      run: |
        xcodebuild test-without-building \
          -project Sudoku.xcodeproj \
          -scheme SudokuTests \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          -configuration Debug \
          CODE_SIGNING_ALLOWED=NO